import {
  formDataSearchInterface,
  formDataThird,
  formDataThirdDef,
  formDataProperty,
  formDataPropertyDef,
  formDataPropertyResultSearch,
  formDataSuscriptionInterface,
  formDataHomologacionInterface,
  filterHomologacionInterface,
  filterSusHomologacion,
  formDataHomologacionOldInterface,
} from "./interfaces";
// valores iniciales del formulario de búsqueda
export const initialFormDataSearch: formDataSearchInterface = {
  docThird: "",
  nameThird: "",
  code: "",
  idSuscription: "",
};
// valores iniciales del formulario de tercero
export const initialDataFormThird: formDataThird = {
  terIderegistro: null,
  terDocumento: "",
  terDigverificacion: null,
  terNombre: "",
  terApellido: "",
  terSexo: "M",
  uniTiptercero: null,
  claterceros: [],
  ciudadCod: "",
  ciudadNombre: "",
  terDocexpedicion: "",
  uniTipidentifica: null,
  terFecnacimiento: "",
  terInfoadicional: null,
  contactosTercero: [],
};
// valores iniciales del formulario de tercero definitivo - el que se envia al backend
export const initialDataFormThirdDef: formDataThirdDef = {
  terIderegistro: null,
  terDocumento: "",
  terDigverificacion: null,
  terNombre: "",
  terApellido: "",
  terSexo: "M",
  uniTiptercero: null,
  claterceros: [],
  ciudadCod: "",
  terDocexpedicion: "",
  uniTipidentifica: null,
  terFecnacimiento: "",
  terInfoadicional: null,
  contactosTercero: [],
};
// valores iniciales del formulario de propiedades
export const initialFormDataProperty: formDataProperty = {
  terIderegistro: 0,
  uniMunicipio: 0,
  uniMunicipioNombre: "",
  uniBarrio: 0,
  uniBarrioNombre: "",
  uniCmpdireccion: 0,
  uniCmpdireccionNombre: "",
  proDireccion: "",
  proNummatriculainmobiliaria: "",
  proNumcatastral: "",
  proNumcatastralnacional: "",
  proDigitos: 0,
  proZona: "U",
  uniTippropieda: 0,
  mubaSector: 0,
  proSeccion: 0,
  proManzana: 0,
  proGpsaltitud: "",
  proGpslatitud: "",
  proGpslongitud: "",
  proAltriesgo: "N",
};
export const initialFormDataPropertyDef: formDataPropertyDef = {
  terIderegistro: 0,
  uniMunicipio: 0,
  uniBarrio: 0,
  uniCmpdireccion: 0,
  proDireccion: "",

  proNumcatastral: "",
  proNumcatastralnacional: "",
  proDigitos: 0,
  proZona: "U",
  uniTippropieda: 0,
  mubaSector: 0,
  proSeccion: 0,
  proManzana: 0,
  proGpsaltitud: "",
  proGpslatitud: "",
  proGpslongitud: "",

  clasificacionViviendaDTOS: [],
  proNummatriculainmobiliaria: "",
  proAltriesgo: "",
  proIdpadre: null,
};

export const initialFormDataPropertyResultSearch: formDataPropertyResultSearch =
  {
    proIderegistro: 0,
    proIdepropieda: "",
    proEstado: "",
    proDescripcion: "",
    proDireccion: "",
    terIderegistro: 0,
    uniTippropieda: 0,
    estTippropieda: 0,
    proDigitos: 0,
    mubaSector: 0,
    proSeccion: 0,
    proManzana: 0,
    uniMunicipio: 0,
    uniBarrio: 0,
    proAltriesgo: "",
    proGpslatitud: "",
    proGpsaltitud: "",
    proGpslongitud: "",
    proNumcatastral: "",
    proZona: "",
    usuIderegistro: 0,
    uniCmpdireccion: 0,
    proResolcatastral: null,
    proFecha: null,
    proNumcatastralnacional: "",
    uniTipovivienda: null,
    proNummatriculainmobiliaria: "",
    uniClasificacionvivienda: [],
    uniMunicipioNombre: "",
    uniBarrioNombre: "",
    uniCmpdireccionNombre: "",
    tippropiedaNombre: "",
  };

export const initCurrentConcept = {
  cosuIdregistr: null,
  uniConcepto: 0,
  fecInicio: "",
  fecFinal: "",
};
export function initialDataFormSuscriptionFuc(): formDataSuscriptionInterface {
  return {
    dsusIderegistr: null,
    susIderegistro: null,
    terIderegistro: 0,
    proIderegistro: 0,
    uniTipsuscripc: 1,
    uniActsuscripc: null,
    cicIderegistro: 0,
    uniTipusosuscr: 0,
    uniLiquidacion: 0,
    proCatestrato: 0,
    dsusEstado: "",
    empIderegistro: null,
    dsusFecinicio: `${new Date()}`,
    dsusDescripcion: "",
    dsusIniestado: `${new Date()}`,
    dsusFinestado: `${new Date()}`,
    dsusFactor: 0.94,
    dsusPcodigo: "",
    empAlternasId: [],
    perIderegistro: null,
    inforadicionalsuscripcionDTO: {
      iasusIderegistro: null,
      iasusCobrojuridico: false,
      iasusPagapeaje: false,
      iasusReferenciacomercial: "",
    },
    recoleccionBarridoDTO: {
      rrbaIdRegistro: null,
      rutIderegistro: 0,
      rutIdMacroRuta: 0,
      rutIderegistroBar: 0,
      rrbaIdRegistroBar: null,
      rutEstado: "A",
      rutEstadoBar: "A",
    },
    rutaAprovechamientoDTO: {
      rutaPrIdRegistro: null,
      terAprovechamiento: 0,
      rutIderegistro: 0,
      terIderegistro: 0,
      incentivo: false,
      aforado: false,
      rutEstado: "A",
    },
    conceptos: [],
  };
}

export function initialDataHomologacionFuc(): formDataHomologacionInterface {
  return {
    ghomIderegistr: null,
    susIderegistro: 0,
    perIderegistro: 0,
    observaciones: "",
    dsusIderegistr: 0,
    cnreIderegistr: 0,
    detalles: [],
  };
}
export function initialDataHomologacionOldFuc(): formDataHomologacionOldInterface {
  return {
    nuevoConvenio: 0,
    nombreNuevoConvenio: "",
    nuevoTercero: 0,
    usuario: null,
    empresaHomologa: 0,
    periodoHomologa: 0,
    dsusHomologa: 0,
    dsusHomologador: 0,
    empresaHomologador: 0,
    pcodigoHomologador: "",
    suscripcion1: 0,
    suscripcion2: 0,
    consumo: "",
    medidor: "",
    observaciones: "",
    deshomologacion: false,
  };
}
export function initialDataFormFilterHomologacion(): filterHomologacionInterface {
  return {
    dsus9dsus_pcodigo: "",
    ter9ter_ideregistro: "",
    ter9ter_documento: "",
    pro9uni_tipovivienda: "",
    dsus9pro_catestrato: "",
    pro9ñpro_direccion: "",
    pro9pro_idepropieda: "",
    proyecto9proyecto_ideregistro: "",
    dsus9uni_barrio: "",
    dsus9dsus_ideregistr: "",
    dsus9uni_tipusosuscr: "",
    pro9pro_numcatastral: "",
    cic9cic_ideregistro: "",
    rut9rut_ideregistro: "",
    dsus9dsus_estado: "",
    empresa: null,
    proidepropieda: "",
    dsusIderegistr: "",
    dsusPcodigo: "",
    empresaSession: "",
    dsus8dsus_fecinicio: "",
    dsus9dsus_fecinicio: "",
  };
}

export function initialFomrFilterSusHomologacion(): filterSusHomologacion {
  return {
    pcodigo: "",
    medidor: "",
    idsus: "",
    idempresa: 0,
    deshomologacion: true,
  };
}
