server.port=9090

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://10.43.51.169:5432/Tecnico
spring.datasource.username=postgres
spring.datasource.password=Coserver.10*
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.type=trace

spring.datasource.hikari.pool-name=LiqNotasPriase
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.max-lifetime=40000

server.tomcat.max-threads=400
jasperTemplatePath=/templates/jrxml/

# Nivel global m\u00ednimo
logging.level.root=ERROR

logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql=ERROR


# Archivo de log
logging.file.name=/opt/wildfly/standalone/log/gellapiservicios.log



