##spring.jpa.hibernate.ddl-auto=none
##spring.jpa.database=POSTGRESQL
##spring.datasource.platform=postgres
##spring.datasource.initialization-mode=always 
spring.datasource.driver-class-name=org.postgresql.Driver
#for local env
#spring.datasource.jndi-name=java:/PostgresDS
#spring.datasource.url=jdbc:postgresql://10.43.51.29:5432/Tecnicoaseo
spring.datasource.url = jdbc:postgresql://10.43.51.68:5432/Tecnico
#spring.datasource.username=asesoftTest
spring.datasource.username=jlmendoza
#spring.datasource.password=Yk33SW94TShQCqzZdojZuVNJ3Kynemv52q
spring.datasource.password=3696dd90fe5473c4f273e220ca3cac49
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=none
server.port=9090
spring.jmx.default-domain=asesoftware
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type=trace
##spring.datasource.hikari.connection-timeout = 20000 
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=3
##spring.datasource.hikari.minimum-idle= 50
##spring.datasource.hikari.maximum-pool-size= 100
##spring.datasource.hikari.idle-timeout=10000 
spring.datasource.hikari.max-lifetime=40000
server.tomcat.max-threads=400
jasperTemplatePath=/templates/jrxml/

##spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

##spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
##spring.jpa.show-sql=true
##spring.jpa.properties.hibernate.format_sql=true
