parameters:
#    libranza.example.class: Libranza\LibranzaBundle\Example

services:
#    libranza.example:
#        class: %libranza.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
