
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://10.43.51.29:5432/Tecnicoaseo
spring.datasource.username=todosistemas
spring.datasource.password=KLVLKZTxWVCqVNS8Y9MzCR9JDucJaCeAvW

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

#logging.level.org.springframework=ERROR
logging.level.com.gell.gestioncartera=ERROR
spring.main.banner-mode=console 
logging.file.name=gellapi.log
#logging.config=logback.xml

#app.version=1.0
#sbpg.init.swagger.title=Gestion de Carteras
#sbpg.init.wagger.description=Core Api Rest para el manejo de Gestion de Carteras