
INSERT INTO aseo.af_departamento (nombre,descripcion)
VALUES
	('ANTIOQUIA','ANTIOQUIA'),
	('ATLANTICO','ATLÁNTICO'),
	('BOGOTA_DC','BOGOTÁ, D.C.'),
	('BOLIVAR','BOLÍVAR'),
	('BOYACA','BOYACÁ'),
	('CALDAS','CALDAS'),
	('CAQUETA','CAQUETÁ'),
	('CAUCA','CAUCA'),
	('CESAR','CESAR'),
	('CORDOBA','CÓRDOBA'),
	('CUNDINAMARCA','CUNDINAMARCA'),
	('CHOCO','CHOCÓ'),
	('HUILA','HUILA'),
	('LA_GUAJIRA','LA GUAJIRA'),
	('MAGDALENA','MAGDALENA'),
	('META','META'),
	('NARIÑO','NARIÑO'),
	('NORTE_DE_SANTANDER','NORTE DE SANTANDER'),
	('QUINDIO','QUINDIO'),
	('RISARALDA','RISARALDA'),
	('SANTANDER','SANTANDER'),
	('SUCRE','SUCRE'),
	('TOLIMA','TOLIMA'),
	('VALLE_DEL_CAUCA','VALLE DEL CAUCA'),
	('ARAUCA','ARAUCA'),
	('CASANARE','CASANARE'),
	('PUTUMAYO','PUTUMAYO'),
	('SAN_ANDRES','ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA'),
	('AMAZONAS','AMAZONAS'),
	('GUAINIA','GUAINÍA'),
	('GUAVIARE','GUAVIARE'),
	('VAUPES','VAUPÉS'),
	('VICHADA','VICHADA');

	
insert into aseo.af_municipio (nombre, descripcion,id_departamento) values
('Abriaquí','Abriaquí',1),
('Acacías','Acacías',16),
('Acandí','Acandí',12),
('Acevedo','Acevedo',13),
('Achí','Achí',4),
('Agrado','Agrado',13),
('Agua de Dios','Agua de Dios',11),
('Aguachica','Aguachica',9),
('Aguada','Aguada',21),
('Aguadas','Aguadas',6),
('Aguazul','Aguazul',26),
('Agustín Codazzi','Agustín Codazzi',9),
('Aipe','Aipe',13),
('Albania','Albania',7),
('Albania','Albania',14),
('Albania','Albania',21),
('Albán','Albán',11),
('Albán San José','Albán San José',17),
('Alcalá','Alcalá',24),
('Alejandria','Alejandria',1),
('Algarrobo','Algarrobo',15),
('Algeciras','Algeciras',13),
('Almaguer','Almaguer',8),
('Almeida','Almeida',5),
('Alpujarra','Alpujarra',23),
('Altamira','Altamira',13),
('Alto Baudó Pie de Pato','Alto Baudó Pie de Pato',12),
('Altos del Rosario','Altos del Rosario',4),
('Alvarado','Alvarado',23),
('Amagá','Amagá',1),
('Amalfi','Amalfi',1),
('Ambalema','Ambalema',23),
('Anapoima','Anapoima',11),
('Ancuya','Ancuya',17),
('Andalucía','Andalucía',24),
('Andes','Andes',1),
('Angelópolis','Angelópolis',1),
('Angostura','Angostura',1),
('Anolaima','Anolaima',11),
('Anorí','Anorí',1),
('Anserma','Anserma',6),
('Ansermanuevo','Ansermanuevo',24),
('Anzoátegui','Anzoátegui',23),
('Anzá','Anzá',1),
('Apartadó','Apartadó',1),
('Apulo','Apulo',11),
('Apía','Apía',20),
('Aquitania','Aquitania',5),
('Aracataca','Aracataca',15),
('Aranzazu','Aranzazu',6),
('Aratoca','Aratoca',21),
('Arauca','Arauca',25),
('Arauquita','Arauquita',25),
('Arbeláez','Arbeláez',11),
('Arboleda Berruecos','Arboleda Berruecos',17),
('Arboledas','Arboledas',18),
('Arboletes','Arboletes',1),
('Arcabuco','Arcabuco',5),
('Arenal','Arenal',4),
('Argelia','Argelia',1),
('Argelia','Argelia',8),
('Argelia','Argelia',24),
('Ariguaní El Difícil','Ariguaní El Difícil',15),
('Arjona','Arjona',4),
('Armenia','Armenia',1),
('Armenia','Armenia',19),
('Armero Guayabal','Armero Guayabal',23),
('Arroyohondo','Arroyohondo',4),
('Astrea','Astrea',9),
('Ataco','Ataco',23),
('Atrato Yuto','Atrato Yuto',12),
('Ayapel','Ayapel',10),
('Bagadó','Bagadó',12),
('Bahía Solano Mútis','Bahía Solano Mútis',12),
('Bajo Baudó Pizarro','Bajo Baudó Pizarro',12),
('Balboa','Balboa',8),
('Balboa','Balboa',20),
('Baranoa','Baranoa',2),
('Baraya','Baraya',13),
('Barbacoas','Barbacoas',17),
('Barbosa','Barbosa',1),
('Barbosa','Barbosa',21),
('Barichara','Barichara',21),
('Barranca de Upía','Barranca de Upía',16),
('Barrancabermeja','Barrancabermeja',21),
('Barrancas','Barrancas',14),
('Barranco de Loba','Barranco de Loba',4),
('Barranquilla','Barranquilla',2),
('Becerríl','Becerríl',9),
('Belalcázar','Belalcázar',6),
('Bello','Bello',1),
('Belmira','Belmira',1),
('Beltrán','Beltrán',11),
('Belén','Belén',5),
('Belén','Belén',17),
('Belén de Bajirá','Belén de Bajirá',12),
('Belén de Umbría','Belén de Umbría',20),
('Belén de los Andaquíes','Belén de los Andaquíes',7),
('Berbeo','Berbeo',5),
('Betania','Betania',1),
('Beteitiva','Beteitiva',5),
('Betulia','Betulia',1),
('Betulia','Betulia',21),
('Bituima','Bituima',11),
('Boavita','Boavita',5),
('Bochalema','Bochalema',18),
('Bogotá D.C.','Bogotá D.C.',3),
('Bojacá','Bojacá',11),
('Bojayá Bellavista','Bojayá Bellavista',12),
('Bolívar','Bolívar',1),
('Bolívar','Bolívar',8),
('Bolívar','Bolívar',21),
('Bolívar','Bolívar',24),
('Bosconia','Bosconia',9),
('Boyacá','Boyacá',5),
('Briceño','Briceño',1),
('Briceño','Briceño',5),
('Bucaramanga','Bucaramanga',21),
('Bucarasica','Bucarasica',18),
('Buenaventura','Buenaventura',24),
('Buenavista','Buenavista',5),
('Buenavista','Buenavista',10),
('Buenavista','Buenavista',19),
('Buenavista','Buenavista',22),
('Buenos Aires','Buenos Aires',8),
('Buesaco','Buesaco',17),
('Buga','Buga',24),
('Bugalagrande','Bugalagrande',24),
('Burítica','Burítica',1),
('Busbanza','Busbanza',5),
('Cabrera','Cabrera',11),
('Cabrera','Cabrera',21),
('Cabuyaro','Cabuyaro',16),
('Cachipay','Cachipay',11),
('Caicedo','Caicedo',1),
('Caicedonia','Caicedonia',24),
('Caimito','Caimito',22),
('Cajamarca','Cajamarca',23),
('Cajibío','Cajibío',8),
('Cajicá','Cajicá',11),
('Calamar','Calamar',4),
('Calamar','Calamar',31),
('Calarcá','Calarcá',19),
('Caldas','Caldas',1),
('Caldas','Caldas',5),
('Caldono','Caldono',8),
('California','California',21),
('Calima Darién','Calima Darién',24),
('Caloto','Caloto',8),
('Calí','Calí',24),
('Campamento','Campamento',1),
('Campo de la Cruz','Campo de la Cruz',2),
('Campoalegre','Campoalegre',13),
('Campohermoso','Campohermoso',5),
('Canalete','Canalete',10),
('Candelaria','Candelaria',2),
('Candelaria','Candelaria',24),
('Cantagallo','Cantagallo',4),
('Cantón de San Pablo','Cantón de San Pablo',12),
('Caparrapí','Caparrapí',11),
('Capitanejo','Capitanejo',21),
('Caracolí','Caracolí',1),
('Caramanta','Caramanta',1),
('Carcasí','Carcasí',21),
('Carepa','Carepa',1),
('Carmen de Apicalá','Carmen de Apicalá',23),
('Carmen de Carupa','Carmen de Carupa',11),
('Carmen de Viboral','Carmen de Viboral',1),
('Carmen del Darién CURBARADÓ','Carmen del Darién CURBARADÓ',12),
('Carolina','Carolina',1),
('Cartagena','Cartagena',4),
('Cartagena del Chairá','Cartagena del Chairá',7),
('Cartago','Cartago',24),
('Carurú','Carurú',32),
('Casabianca','Casabianca',23),
('Castilla la Nueva','Castilla la Nueva',16),
('Caucasia','Caucasia',1),
('Cañasgordas','Cañasgordas',1),
('Cepita','Cepita',21),
('Cereté','Cereté',10),
('Cerinza','Cerinza',5),
('Cerrito','Cerrito',21),
('Cerro San Antonio','Cerro San Antonio',15),
('Chachaguí','Chachaguí',17),
('Chaguaní','Chaguaní',11),
('Chalán','Chalán',22),
('Chaparral','Chaparral',23),
('Charalá','Charalá',21),
('Charta','Charta',21),
('Chigorodó','Chigorodó',1),
('Chima','Chima',21),
('Chimichagua','Chimichagua',9),
('Chimá','Chimá',10),
('Chinavita','Chinavita',5),
('Chinchiná','Chinchiná',6),
('Chinácota','Chinácota',18),
('Chinú','Chinú',10),
('Chipaque','Chipaque',11),
('Chipatá','Chipatá',21),
('Chiquinquirá','Chiquinquirá',5),
('Chiriguaná','Chiriguaná',9),
('Chiscas','Chiscas',5),
('Chita','Chita',5),
('Chitagá','Chitagá',18),
('Chitaraque','Chitaraque',5),
('Chivatá','Chivatá',5),
('Chivolo','Chivolo',15),
('Choachí','Choachí',11),
('Chocontá','Chocontá',11),
('Chámeza','Chámeza',26),
('Chía','Chía',11),
('Chíquiza','Chíquiza',5),
('Chívor','Chívor',5),
('Cicuco','Cicuco',4),
('Cimitarra','Cimitarra',21),
('Circasia','Circasia',19),
('Cisneros','Cisneros',1),
('Ciénaga','Ciénaga',5),
('Ciénaga','Ciénaga',15),
('Ciénaga de Oro','Ciénaga de Oro',10),
('Clemencia','Clemencia',4),
('Cocorná','Cocorná',1),
('Coello','Coello',23),
('Cogua','Cogua',11),
('Colombia','Colombia',13),
('Colosó Ricaurte','Colosó Ricaurte',22),
('Colón','Colón',27),
('Colón Génova','Colón Génova',17),
('Concepción','Concepción',1),
('Concepción','Concepción',21),
('Concordia','Concordia',1),
('Concordia','Concordia',15),
('Condoto','Condoto',12),
('Confines','Confines',21),
('Consaca','Consaca',17),
('Contadero','Contadero',17),
('Contratación','Contratación',21),
('Convención','Convención',18),
('Copacabana','Copacabana',1),
('Coper','Coper',5),
('Cordobá','Cordobá',19),
('Corinto','Corinto',8),
('Coromoro','Coromoro',21),
('Corozal','Corozal',22),
('Corrales','Corrales',5),
('Cota','Cota',11),
('Cotorra','Cotorra',10),
('Covarachía','Covarachía',5),
('Coveñas','Coveñas',22),
('Coyaima','Coyaima',23),
('Cravo Norte','Cravo Norte',25),
('Cuaspud Carlosama','Cuaspud Carlosama',17),
('Cubarral','Cubarral',16),
('Cubará','Cubará',5),
('Cucaita','Cucaita',5),
('Cucunubá','Cucunubá',11),
('Cucutilla','Cucutilla',18),
('Cuitiva','Cuitiva',5),
('Cumaral','Cumaral',16),
('Cumaribo','Cumaribo',33),
('Cumbal','Cumbal',17),
('Cumbitara','Cumbitara',17),
('Cunday','Cunday',23),
('Curillo','Curillo',7),
('Curití','Curití',21),
('Curumaní','Curumaní',9),
('Cáceres','Cáceres',1),
('Cáchira','Cáchira',18),
('Cácota','Cácota',18),
('Cáqueza','Cáqueza',11),
('Cértegui','Cértegui',12),
('Cómbita','Cómbita',5),
('Córdoba','Córdoba',4),
('Córdoba','Córdoba',17),
('Cúcuta','Cúcuta',18),
('Dabeiba','Dabeiba',1),
('Dagua','Dagua',24),
('Dibulla','Dibulla',14),
('Distracción','Distracción',14),
('Dolores','Dolores',23),
('Don Matías','Don Matías',1),
('Dos Quebradas','Dos Quebradas',20),
('Duitama','Duitama',5),
('Durania','Durania',18),
('Ebéjico','Ebéjico',1),
('El Bagre','El Bagre',1),
('El Banco','El Banco',15),
('El Cairo','El Cairo',24),
('El Calvario','El Calvario',16),
('El Carmen','El Carmen',18),
('El Carmen','El Carmen',21),
('El Carmen de Atrato','El Carmen de Atrato',12),
('El Carmen de Bolívar','El Carmen de Bolívar',4),
('El Castillo','El Castillo',16),
('El Cerrito','El Cerrito',24),
('El Charco','El Charco',17),
('El Cocuy','El Cocuy',5),
('El Colegio','El Colegio',11),
('El Copey','El Copey',9),
('El Doncello','El Doncello',7),
('El Dorado','El Dorado',16),
('El Dovio','El Dovio',24),
('El Espino','El Espino',5),
('El Guacamayo','El Guacamayo',21),
('El Guamo','El Guamo',4),
('El Molino','El Molino',14),
('El Paso','El Paso',9),
('El Paujil','El Paujil',7),
('El Peñol','El Peñol',17),
('El Peñon','El Peñon',4),
('El Peñon','El Peñon',21),
('El Peñón','El Peñón',11),
('El Piñon','El Piñon',15),
('El Playón','El Playón',21),
('El Retorno','El Retorno',31),
('El Retén','El Retén',15),
('El Roble','El Roble',22),
('El Rosal','El Rosal',11),
('El Rosario','El Rosario',17),
('El Tablón de Gómez','El Tablón de Gómez',17),
('El Tambo','El Tambo',8),
('El Tambo','El Tambo',17),
('El Tarra','El Tarra',18),
('El Zulia','El Zulia',18),
('El Águila','El Águila',24),
('Elías','Elías',13),
('Encino','Encino',21),
('Enciso','Enciso',21),
('Entrerríos','Entrerríos',1),
('Envigado','Envigado',1),
('Espinal','Espinal',23),
('Facatativá','Facatativá',11),
('Falan','Falan',23),
('Filadelfia','Filadelfia',6),
('Filandia','Filandia',19),
('Firavitoba','Firavitoba',5),
('Flandes','Flandes',23),
('Florencia','Florencia',7),
('Florencia','Florencia',8),
('Floresta','Floresta',5),
('Florida','Florida',24),
('Floridablanca','Floridablanca',21),
('Florián','Florián',21),
('Fonseca','Fonseca',14),
('Fortúl','Fortúl',25),
('Fosca','Fosca',11),
('Francisco Pizarro','Francisco Pizarro',17),
('Fredonia','Fredonia',1),
('Fresno','Fresno',23),
('Frontino','Frontino',1),
('Fuente de Oro','Fuente de Oro',16),
('Fundación','Fundación',15),
('Funes','Funes',17),
('Funza','Funza',11),
('Fusagasugá','Fusagasugá',11),
('Fómeque','Fómeque',11),
('Fúquene','Fúquene',11),
('Gachalá','Gachalá',11),
('Gachancipá','Gachancipá',11),
('Gachantivá','Gachantivá',5),
('Gachetá','Gachetá',11),
('Galapa','Galapa',2),
('Galeras Nueva Granada','Galeras Nueva Granada',22),
('Galán','Galán',21),
('Gama','Gama',11),
('Gamarra','Gamarra',9),
('Garagoa','Garagoa',5),
('Garzón','Garzón',13),
('Gigante','Gigante',13),
('Ginebra','Ginebra',24),
('Giraldo','Giraldo',1),
('Girardot','Girardot',11),
('Girardota','Girardota',1),
('Girón','Girón',21),
('Gonzalez','Gonzalez',9),
('Gramalote','Gramalote',18),
('Granada','Granada',1),
('Granada','Granada',11),
('Granada','Granada',16),
('Guaca','Guaca',21),
('Guacamayas','Guacamayas',5),
('Guacarí','Guacarí',24),
('Guachavés','Guachavés',17),
('Guachené','Guachené',8),
('Guachetá','Guachetá',11),
('Guachucal','Guachucal',17),
('Guadalupe','Guadalupe',1),
('Guadalupe','Guadalupe',13),
('Guadalupe','Guadalupe',21),
('Guaduas','Guaduas',11),
('Guaitarilla','Guaitarilla',17),
('Gualmatán','Gualmatán',17),
('Guamal','Guamal',15),
('Guamal','Guamal',16),
('Guamo','Guamo',23),
('Guapota','Guapota',21),
('Guapí','Guapí',8),
('Guaranda','Guaranda',22),
('Guarne','Guarne',1),
('Guasca','Guasca',11),
('Guatapé','Guatapé',1),
('Guataquí','Guataquí',11),
('Guatavita','Guatavita',11),
('Guateque','Guateque',5),
('Guavatá','Guavatá',21),
('Guayabal de Siquima','Guayabal de Siquima',11),
('Guayabetal','Guayabetal',11),
('Guayatá','Guayatá',5),
('Guepsa','Guepsa',21),
('Guicán','Guicán',5),
('Gutiérrez','Gutiérrez',11),
('Guática','Guática',20),
('Gámbita','Gámbita',21),
('Gámeza','Gámeza',5),
('Génova','Génova',19),
('Gómez Plata','Gómez Plata',1),
('Hacarí','Hacarí',18),
('Hatillo de Loba','Hatillo de Loba',4),
('Hato','Hato',21),
('Hato Corozal','Hato Corozal',26),
('Hatonuevo','Hatonuevo',14),
('Heliconia','Heliconia',1),
('Herrán','Herrán',18),
('Herveo','Herveo',23),
('Hispania','Hispania',1),
('Hobo','Hobo',13),
('Honda','Honda',23),
('Ibagué','Ibagué',23),
('Icononzo','Icononzo',23),
('Iles','Iles',17),
('Imúes','Imúes',17),
('Inzá','Inzá',8),
('Inírida','Inírida',30),
('Ipiales','Ipiales',17),
('Isnos','Isnos',13),
('Istmina','Istmina',12),
('Itagüí','Itagüí',1),
('Ituango','Ituango',1),
('Izá','Izá',5),
('Jambaló','Jambaló',8),
('Jamundí','Jamundí',24),
('Jardín','Jardín',1),
('Jenesano','Jenesano',5),
('Jericó','Jericó',1),
('Jericó','Jericó',5),
('Jerusalén','Jerusalén',11),
('Jesús María','Jesús María',21),
('Jordán','Jordán',21),
('Juan de Acosta','Juan de Acosta',2),
('Junín','Junín',11),
('Juradó','Juradó',12),
('La Apartada y La Frontera','La Apartada y La Frontera',10),
('La Argentina','La Argentina',13),
('La Belleza','La Belleza',21),
('La Calera','La Calera',11),
('La Capilla','La Capilla',5),
('La Ceja','La Ceja',1),
('La Celia','La Celia',20),
('La Cruz','La Cruz',17),
('La Cumbre','La Cumbre',24),
('La Dorada','La Dorada',6),
('La Esperanza','La Esperanza',18),
('La Estrella','La Estrella',1),
('La Florida','La Florida',17),
('La Gloria','La Gloria',9),
('La Jagua de Ibirico','La Jagua de Ibirico',9),
('La Jagua del Pilar','La Jagua del Pilar',14),
('La Llanada','La Llanada',17),
('La Macarena','La Macarena',16),
('La Merced','La Merced',6),
('La Mesa','La Mesa',11),
('La Montañita','La Montañita',7),
('La Palma','La Palma',11),
('La Paz','La Paz',21),
('La Paz Robles','La Paz Robles',9),
('La Peña','La Peña',11),
('La Pintada','La Pintada',1),
('La Plata','La Plata',13),
('La Playa','La Playa',18),
('La Primavera','La Primavera',33),
('La Salina','La Salina',26),
('La Sierra','La Sierra',8),
('La Tebaida','La Tebaida',19),
('La Tola','La Tola',17),
('La Unión','La Unión',1),
('La Unión','La Unión',17),
('La Unión','La Unión',22),
('La Unión','La Unión',24),
('La Uvita','La Uvita',5),
('La Vega','La Vega',8),
('La Vega','La Vega',11),
('La Victoria','La Victoria',5),
('La Victoria','La Victoria',6),
('La Victoria','La Victoria',24),
('La Virginia','La Virginia',20),
('Labateca','Labateca',18),
('Labranzagrande','Labranzagrande',5),
('Landázuri','Landázuri',21),
('Lebrija','Lebrija',21),
('Leiva','Leiva',17),
('Lejanías','Lejanías',16),
('Lenguazaque','Lenguazaque',11),
('Leticia','Leticia',29),
('Liborina','Liborina',1),
('Linares','Linares',17),
('Lloró','Lloró',12),
('Lorica','Lorica',10),
('Los Córdobas','Los Córdobas',10),
('Los Palmitos','Los Palmitos',22),
('Los Patios','Los Patios',18),
('Los Santos','Los Santos',21),
('Lourdes','Lourdes',18),
('Luruaco','Luruaco',2),
('Lérida','Lérida',23),
('Líbano','Líbano',23),
('López Micay','López Micay',8),
('Macanal','Macanal',5),
('Macaravita','Macaravita',21),
('Maceo','Maceo',1),
('Machetá','Machetá',11),
('Madrid','Madrid',11),
('Magangué','Magangué',4),
('Magüi Payán','Magüi Payán',17),
('Mahates','Mahates',4),
('Maicao','Maicao',14),
('Majagual','Majagual',22),
('Malambo','Malambo',2),
('Mallama Piedrancha','Mallama Piedrancha',17),
('Manatí','Manatí',2),
('Manaure','Manaure',14),
('Manaure Balcón del Cesar','Manaure Balcón del Cesar',9),
('Manizales','Manizales',6),
('Manta','Manta',11),
('Manzanares','Manzanares',6),
('Maní','Maní',26),
('Mapiripan','Mapiripan',16),
('Margarita','Margarita',4),
('Marinilla','Marinilla',1),
('Maripí','Maripí',5),
('Mariquita','Mariquita',23),
('Marmato','Marmato',6),
('Marquetalia','Marquetalia',6),
('Marsella','Marsella',20),
('Marulanda','Marulanda',6),
('María la Baja','María la Baja',4),
('Matanza','Matanza',21),
('Medellín','Medellín',1),
('Medina','Medina',11),
('Medio Atrato','Medio Atrato',12),
('Medio Baudó','Medio Baudó',12),
('Medio San Juan ANDAGOYA','Medio San Juan ANDAGOYA',12),
('Melgar','Melgar',23),
('Mercaderes','Mercaderes',8),
('Mesetas','Mesetas',16),
('Milán','Milán',7),
('Miraflores','Miraflores',5),
('Miraflores','Miraflores',31),
('Miranda','Miranda',8),
('Mistrató','Mistrató',20),
('Mitú','Mitú',32),
('Mocoa','Mocoa',27),
('Mogotes','Mogotes',21),
('Molagavita','Molagavita',21),
('Momil','Momil',10),
('Mompós','Mompós',4),
('Mongua','Mongua',5),
('Monguí','Monguí',5),
('Moniquirá','Moniquirá',5),
('Montebello','Montebello',1),
('Montecristo','Montecristo',4),
('Montelíbano','Montelíbano',10),
('Montenegro','Montenegro',19),
('Monteria','Monteria',10),
('Monterrey','Monterrey',26),
('Morales','Morales',4),
('Morales','Morales',8),
('Morelia','Morelia',7),
('Morroa','Morroa',22),
('Mosquera','Mosquera',11),
('Mosquera','Mosquera',17),
('Motavita','Motavita',5),
('Moñitos','Moñitos',10),
('Murillo','Murillo',23),
('Murindó','Murindó',1),
('Mutatá','Mutatá',1),
('Mutiscua','Mutiscua',18),
('Muzo','Muzo',5),
('Málaga','Málaga',21),
('Nariño','Nariño',1),
('Nariño','Nariño',11),
('Nariño','Nariño',17),
('Natagaima','Natagaima',23),
('Nechí','Nechí',1),
('Necoclí','Necoclí',1),
('Neira','Neira',6),
('Neiva','Neiva',13),
('Nemocón','Nemocón',11),
('Nilo','Nilo',11),
('Nimaima','Nimaima',11),
('Nobsa','Nobsa',5),
('Nocaima','Nocaima',11),
('Norcasia','Norcasia',6),
('Norosí','Norosí',4),
('Novita','Novita',12),
('Nueva Granada','Nueva Granada',15),
('Nuevo Colón','Nuevo Colón',5),
('Nunchía','Nunchía',26),
('Nuquí','Nuquí',12),
('Nátaga','Nátaga',13),
('Obando','Obando',24),
('Ocamonte','Ocamonte',21),
('Ocaña','Ocaña',18),
('Oiba','Oiba',21),
('Oicatá','Oicatá',5),
('Olaya','Olaya',1),
('Olaya Herrera','Olaya Herrera',17),
('Onzaga','Onzaga',21),
('Oporapa','Oporapa',13),
('Orito','Orito',27),
('Orocué','Orocué',26),
('Ortega','Ortega',23),
('Ospina','Ospina',17),
('Otanche','Otanche',5),
('Ovejas','Ovejas',22),
('Pachavita','Pachavita',5),
('Pacho','Pacho',11),
('Padilla','Padilla',8),
('Paicol','Paicol',13),
('Pailitas','Pailitas',9),
('Paime','Paime',11),
('Paipa','Paipa',5),
('Pajarito','Pajarito',5),
('Palermo','Palermo',13),
('Palestina','Palestina',6),
('Palestina','Palestina',13),
('Palmar','Palmar',21),
('Palmar de Varela','Palmar de Varela',2),
('Palmas del Socorro','Palmas del Socorro',21),
('Palmira','Palmira',24),
('Palmito','Palmito',22),
('Palocabildo','Palocabildo',23),
('Pamplona','Pamplona',18),
('Pamplonita','Pamplonita',18),
('Pandi','Pandi',11),
('Panqueba','Panqueba',5),
('Paratebueno','Paratebueno',11),
('Pasca','Pasca',11),
('Patía El Bordo','Patía El Bordo',8),
('Pauna','Pauna',5),
('Paya','Paya',5),
('Paz de Ariporo','Paz de Ariporo',26),
('Paz de Río','Paz de Río',5),
('Pedraza','Pedraza',15),
('Pelaya','Pelaya',9),
('Pensilvania','Pensilvania',6),
('Peque','Peque',1),
('Pereira','Pereira',20),
('Pesca','Pesca',5),
('Peñol','Peñol',1),
('Piamonte','Piamonte',8),
('Pie de Cuesta','Pie de Cuesta',21),
('Piedras','Piedras',23),
('Piendamó','Piendamó',8),
('Pijao','Pijao',19),
('Pijiño','Pijiño',15),
('Pinchote','Pinchote',21),
('Pinillos','Pinillos',4),
('Piojo','Piojo',2),
('Pisva','Pisva',5),
('Pital','Pital',13),
('Pitalito','Pitalito',13),
('Pivijay','Pivijay',15),
('Planadas','Planadas',23),
('Planeta Rica','Planeta Rica',10),
('Plato','Plato',15),
('Policarpa','Policarpa',17),
('Polonuevo','Polonuevo',2),
('Ponedera','Ponedera',2),
('Popayán','Popayán',8),
('Pore','Pore',26),
('Potosí','Potosí',17),
('Pradera','Pradera',24),
('Prado','Prado',23),
('Providencia','Providencia',17),
('Providencia','Providencia',28),
('Pueblo Bello','Pueblo Bello',9),
('Pueblo Nuevo','Pueblo Nuevo',10),
('Pueblo Rico','Pueblo Rico',20),
('Pueblorrico','Pueblorrico',1),
('Puebloviejo','Puebloviejo',15),
('Puente Nacional','Puente Nacional',21),
('Puerres','Puerres',17),
('Puerto Asís','Puerto Asís',27),
('Puerto Berrío','Puerto Berrío',1),
('Puerto Boyacá','Puerto Boyacá',5),
('Puerto Caicedo','Puerto Caicedo',27),
('Puerto Carreño','Puerto Carreño',33),
('Puerto Colombia','Puerto Colombia',2),
('Puerto Concordia','Puerto Concordia',16),
('Puerto Escondido','Puerto Escondido',10),
('Puerto Gaitán','Puerto Gaitán',16),
('Puerto Guzmán','Puerto Guzmán',27),
('Puerto Leguízamo','Puerto Leguízamo',27),
('Puerto Libertador','Puerto Libertador',10),
('Puerto Lleras','Puerto Lleras',16),
('Puerto López','Puerto López',16),
('Puerto Nare','Puerto Nare',1),
('Puerto Nariño','Puerto Nariño',29),
('Puerto Parra','Puerto Parra',21),
('Puerto Rico','Puerto Rico',7),
('Puerto Rico','Puerto Rico',16),
('Puerto Rondón','Puerto Rondón',25),
('Puerto Salgar','Puerto Salgar',11),
('Puerto Santander','Puerto Santander',18),
('Puerto Tejada','Puerto Tejada',8),
('Puerto Triunfo','Puerto Triunfo',1),
('Puerto Wilches','Puerto Wilches',21),
('Pulí','Pulí',11),
('Pupiales','Pupiales',17),
('Puracé Coconuco','Puracé Coconuco',8),
('Purificación','Purificación',23),
('Purísima','Purísima',10),
('Pácora','Pácora',6),
('Páez','Páez',5),
('Páez Belalcazar','Páez Belalcazar',8),
('Páramo','Páramo',21),
('Quebradanegra','Quebradanegra',11),
('Quetame','Quetame',11),
('Quibdó','Quibdó',12),
('Quimbaya','Quimbaya',19),
('Quinchía','Quinchía',20),
('Quipama','Quipama',5),
('Quipile','Quipile',11),
('Ragonvalia','Ragonvalia',18),
('Ramiriquí','Ramiriquí',5),
('Recetor','Recetor',26),
('Regidor','Regidor',4),
('Remedios','Remedios',1),
('Remolino','Remolino',15),
('Repelón','Repelón',2),
('Restrepo','Restrepo',16),
('Restrepo','Restrepo',24),
('Retiro','Retiro',1),
('Ricaurte','Ricaurte',11),
('Ricaurte','Ricaurte',17),
('Rio Negro','Rio Negro',21),
('Rioblanco','Rioblanco',23),
('Riofrío','Riofrío',24),
('Riohacha','Riohacha',14),
('Risaralda','Risaralda',6),
('Rivera','Rivera',13),
('Roberto Payán San José','Roberto Payán San José',17),
('Roldanillo','Roldanillo',24),
('Roncesvalles','Roncesvalles',23),
('Rondón','Rondón',5),
('Rosas','Rosas',8),
('Rovira','Rovira',23),
('Ráquira','Ráquira',5),
('Río Iró','Río Iró',12),
('Río Quito','Río Quito',12),
('Río Sucio','Río Sucio',6),
('Río Viejo','Río Viejo',4),
('Río de oro','Río de oro',9),
('Ríonegro','Ríonegro',1),
('Ríosucio','Ríosucio',12),
('Sabana de Torres','Sabana de Torres',21),
('Sabanagrande','Sabanagrande',2),
('Sabanalarga','Sabanalarga',1),
('Sabanalarga','Sabanalarga',2),
('Sabanalarga','Sabanalarga',26),
('Sabanas de San Angel SAN ANGEL','Sabanas de San Angel SAN ANGEL',15),
('Sabaneta','Sabaneta',1),
('Saboyá','Saboyá',5),
('Sahagún','Sahagún',10),
('Saladoblanco','Saladoblanco',13),
('Salamina','Salamina',6),
('Salamina','Salamina',15),
('Salazar','Salazar',18),
('Saldaña','Saldaña',23),
('Salento','Salento',19),
('Salgar','Salgar',1),
('Samacá','Samacá',5),
('Samaniego','Samaniego',17),
('Samaná','Samaná',6),
('Sampués','Sampués',22),
('San Agustín','San Agustín',13),
('San Alberto','San Alberto',9),
('San Andrés','San Andrés',21),
('San Andrés Sotavento','San Andrés Sotavento',10),
('San Andrés de Cuerquía','San Andrés de Cuerquía',1),
('San Antero','San Antero',10),
('San Antonio','San Antonio',23),
('San Antonio de Tequendama','San Antonio de Tequendama',11),
('San Benito','San Benito',21),
('San Benito Abad','San Benito Abad',22),
('San Bernardo','San Bernardo',11),
('San Bernardo','San Bernardo',17),
('San Bernardo del Viento','San Bernardo del Viento',10),
('San Calixto','San Calixto',18),
('San Carlos','San Carlos',1),
('San Carlos','San Carlos',10),
('San Carlos de Guaroa','San Carlos de Guaroa',16),
('San Cayetano','San Cayetano',11),
('San Cayetano','San Cayetano',18),
('San Cristobal','San Cristobal',4),
('San Diego','San Diego',9),
('San Eduardo','San Eduardo',5),
('San Estanislao','San Estanislao',4),
('San Fernando','San Fernando',4),
('San Francisco','San Francisco',1),
('San Francisco','San Francisco',11),
('San Francisco','San Francisco',27),
('San Gíl','San Gíl',21),
('San Jacinto','San Jacinto',4),
('San Jacinto del Cauca','San Jacinto del Cauca',4),
('San Jerónimo','San Jerónimo',1),
('San Joaquín','San Joaquín',21),
('San José','San José',6),
('San José de Miranda','San José de Miranda',21),
('San José de Montaña','San José de Montaña',1),
('San José de Pare','San José de Pare',5),
('San José de Uré','San José de Uré',10),
('San José del Fragua','San José del Fragua',7),
('San José del Guaviare','San José del Guaviare',31),
('San José del Palmar','San José del Palmar',12),
('San Juan de Arama','San Juan de Arama',16),
('San Juan de Betulia','San Juan de Betulia',22),
('San Juan de Nepomuceno','San Juan de Nepomuceno',4),
('San Juan de Pasto','San Juan de Pasto',17),
('San Juan de Río Seco','San Juan de Río Seco',11),
('San Juan de Urabá','San Juan de Urabá',1),
('San Juan del Cesar','San Juan del Cesar',14),
('San Juanito','San Juanito',16),
('San Lorenzo','San Lorenzo',17),
('San Luis','San Luis',23),
('San Luís','San Luís',1),
('San Luís de Gaceno','San Luís de Gaceno',5),
('San Luís de Palenque','San Luís de Palenque',26),
('San Marcos','San Marcos',22),
('San Martín','San Martín',9),
('San Martín','San Martín',16),
('San Martín de Loba','San Martín de Loba',4),
('San Mateo','San Mateo',5),
('San Miguel','San Miguel',21),
('San Miguel','San Miguel',27),
('San Miguel de Sema','San Miguel de Sema',5),
('San Onofre','San Onofre',22),
('San Pablo','San Pablo',4),
('San Pablo','San Pablo',17),
('San Pablo de Borbur','San Pablo de Borbur',5),
('San Pedro','San Pedro',1),
('San Pedro','San Pedro',22),
('San Pedro','San Pedro',24),
('San Pedro de Cartago','San Pedro de Cartago',17),
('San Pedro de Urabá','San Pedro de Urabá',1),
('San Pelayo','San Pelayo',10),
('San Rafael','San Rafael',1),
('San Roque','San Roque',1),
('San Sebastián','San Sebastián',8),
('San Sebastián de Buenavista','San Sebastián de Buenavista',15),
('San Vicente','San Vicente',1),
('San Vicente del Caguán','San Vicente del Caguán',7),
('San Vicente del Chucurí','San Vicente del Chucurí',21),
('San Zenón','San Zenón',15),
('Sandoná','Sandoná',17),
('Santa Ana','Santa Ana',15),
('Santa Bárbara','Santa Bárbara',1),
('Santa Bárbara','Santa Bárbara',21),
('Santa Bárbara Iscuandé','Santa Bárbara Iscuandé',17),
('Santa Bárbara de Pinto','Santa Bárbara de Pinto',15),
('Santa Catalina','Santa Catalina',4),
('Santa Fé de Antioquia','Santa Fé de Antioquia',1),
('Santa Genoveva de Docorodó','Santa Genoveva de Docorodó',12),
('Santa Helena del Opón','Santa Helena del Opón',21),
('Santa Isabel','Santa Isabel',23),
('Santa Lucía','Santa Lucía',2),
('Santa Marta','Santa Marta',15),
('Santa María','Santa María',5),
('Santa María','Santa María',13),
('Santa Rosa','Santa Rosa',4),
('Santa Rosa','Santa Rosa',8),
('Santa Rosa de Cabal','Santa Rosa de Cabal',20),
('Santa Rosa de Osos','Santa Rosa de Osos',1),
('Santa Rosa de Viterbo','Santa Rosa de Viterbo',5),
('Santa Rosa del Sur','Santa Rosa del Sur',4),
('Santa Rosalía','Santa Rosalía',33),
('Santa Sofía','Santa Sofía',5),
('Santana','Santana',5),
('Santander de Quilichao','Santander de Quilichao',8),
('Santiago','Santiago',18),
('Santiago','Santiago',27),
('Santo Domingo','Santo Domingo',1),
('Santo Tomás','Santo Tomás',2),
('Santuario','Santuario',1),
('Santuario','Santuario',20),
('Sapuyes','Sapuyes',17),
('Saravena','Saravena',25),
('Sardinata','Sardinata',18),
('Sasaima','Sasaima',11),
('Sativanorte','Sativanorte',5),
('Sativasur','Sativasur',5),
('Segovia','Segovia',1),
('Sesquilé','Sesquilé',11),
('Sevilla','Sevilla',24),
('Siachoque','Siachoque',5),
('Sibaté','Sibaté',11),
('Sibundoy','Sibundoy',27),
('Silos','Silos',18),
('Silvania','Silvania',11),
('Silvia','Silvia',8),
('Simacota','Simacota',21),
('Simijaca','Simijaca',11),
('Simití','Simití',4),
('Sincelejo','Sincelejo',22),
('Sincé','Sincé',22),
('Sipí','Sipí',12),
('Sitionuevo','Sitionuevo',15),
('Soacha','Soacha',11),
('Soatá','Soatá',5),
('Socha','Socha',5),
('Socorro','Socorro',21),
('Socotá','Socotá',5),
('Sogamoso','Sogamoso',5),
('Solano','Solano',7),
('Soledad','Soledad',2),
('Solita','Solita',7),
('Somondoco','Somondoco',5),
('Sonsón','Sonsón',1),
('Sopetrán','Sopetrán',1),
('Soplaviento','Soplaviento',4),
('Sopó','Sopó',11),
('Sora','Sora',5),
('Soracá','Soracá',5),
('Sotaquirá','Sotaquirá',5),
('Sotara Paispamba','Sotara Paispamba',8),
('Sotomayor Los Andes','Sotomayor Los Andes',17),
('Suaita','Suaita',21),
('Suan','Suan',2),
('Suaza','Suaza',13),
('Subachoque','Subachoque',11),
('Sucre','Sucre',8),
('Sucre','Sucre',21),
('Sucre','Sucre',22),
('Suesca','Suesca',11),
('Supatá','Supatá',11),
('Supía','Supía',6),
('Suratá','Suratá',21),
('Susa','Susa',11),
('Susacón','Susacón',5),
('Sutamarchán','Sutamarchán',5),
('Sutatausa','Sutatausa',11),
('Sutatenza','Sutatenza',5),
('Suárez','Suárez',8),
('Suárez','Suárez',23),
('Sácama','Sácama',26),
('Sáchica','Sáchica',5),
('Tabio','Tabio',11),
('Tadó','Tadó',12),
('Talaigua Nuevo','Talaigua Nuevo',4),
('Tamalameque','Tamalameque',9),
('Tame','Tame',25),
('Taminango','Taminango',17),
('Tangua','Tangua',17),
('Taraira','Taraira',32),
('Tarazá','Tarazá',1),
('Tarqui','Tarqui',13),
('Tarso','Tarso',1),
('Tasco','Tasco',5),
('Tauramena','Tauramena',26),
('Tausa','Tausa',11),
('Tello','Tello',13),
('Tena','Tena',11),
('Tenerife','Tenerife',15),
('Tenjo','Tenjo',11),
('Tenza','Tenza',5),
('Teorama','Teorama',18),
('Teruel','Teruel',13),
('Tesalia','Tesalia',13),
('Tibacuy','Tibacuy',11),
('Tibaná','Tibaná',5),
('Tibasosa','Tibasosa',5),
('Tibirita','Tibirita',11),
('Tibú','Tibú',18),
('Tierralta','Tierralta',10),
('Timaná','Timaná',13),
('Timbiquí','Timbiquí',8),
('Timbío','Timbío',8),
('Tinjacá','Tinjacá',5),
('Tipacoque','Tipacoque',5),
('Tiquisio Puerto Rico','Tiquisio Puerto Rico',4),
('Titiribí','Titiribí',1),
('Toca','Toca',5),
('Tocaima','Tocaima',11),
('Tocancipá','Tocancipá',11),
('Toguí','Toguí',5),
('Toledo','Toledo',1),
('Toledo','Toledo',18),
('Tolú','Tolú',22),
('Tolú Viejo','Tolú Viejo',22),
('Tona','Tona',21),
('Topagá','Topagá',5),
('Topaipí','Topaipí',11),
('Toribío','Toribío',8),
('Toro','Toro',24),
('Tota','Tota',5),
('Totoró','Totoró',8),
('Trinidad','Trinidad',26),
('Trujillo','Trujillo',24),
('Tubará','Tubará',2),
('Tuchín','Tuchín',10),
('Tulúa','Tulúa',24),
('Tumaco','Tumaco',17),
('Tunja','Tunja',5),
('Tunungua','Tunungua',5),
('Turbaco','Turbaco',4),
('Turbaná','Turbaná',4),
('Turbo','Turbo',1),
('Turmequé','Turmequé',5),
('Tuta','Tuta',5),
('Tutasá','Tutasá',5),
('Támara','Támara',26),
('Támesis','Támesis',1),
('Túquerres','Túquerres',17),
('Ubalá','Ubalá',11),
('Ubaque','Ubaque',11),
('Ubaté','Ubaté',11),
('Ulloa','Ulloa',24),
('Une','Une',11),
('Unguía','Unguía',12),
('Unión Panamericana ÁNIMAS','Unión Panamericana ÁNIMAS',12),
('Uramita','Uramita',1),
('Uribe','Uribe',16),
('Uribia','Uribia',14),
('Urrao','Urrao',1),
('Urumita','Urumita',14),
('Usiacuri','Usiacuri',2),
('Valdivia','Valdivia',1),
('Valencia','Valencia',10),
('Valle de San José','Valle de San José',21),
('Valle de San Juan','Valle de San Juan',23),
('Valle del Guamuez','Valle del Guamuez',27),
('Valledupar','Valledupar',9),
('Valparaiso','Valparaiso',1),
('Valparaiso','Valparaiso',7),
('Vegachí','Vegachí',1),
('Venadillo','Venadillo',23),
('Venecia','Venecia',1),
('Venecia Ospina Pérez','Venecia Ospina Pérez',11),
('Ventaquemada','Ventaquemada',5),
('Vergara','Vergara',11),
('Versalles','Versalles',24),
('Vetas','Vetas',21),
('Viani','Viani',11),
('Vigía del Fuerte','Vigía del Fuerte',1),
('Vijes','Vijes',24),
('Villa Caro','Villa Caro',18),
('Villa Rica','Villa Rica',8),
('Villa de Leiva','Villa de Leiva',5),
('Villa del Rosario','Villa del Rosario',18),
('Villagarzón','Villagarzón',27),
('Villagómez','Villagómez',11),
('Villahermosa','Villahermosa',23),
('Villamaría','Villamaría',6),
('Villanueva','Villanueva',4),
('Villanueva','Villanueva',14),
('Villanueva','Villanueva',21),
('Villanueva','Villanueva',26),
('Villapinzón','Villapinzón',11),
('Villarrica','Villarrica',23),
('Villavicencio','Villavicencio',16),
('Villavieja','Villavieja',13),
('Villeta','Villeta',11),
('Viotá','Viotá',11),
('Viracachá','Viracachá',5),
('Vista Hermosa','Vista Hermosa',16),
('Viterbo','Viterbo',6),
('Vélez','Vélez',21),
('Yacopí','Yacopí',11),
('Yacuanquer','Yacuanquer',17),
('Yaguará','Yaguará',13),
('Yalí','Yalí',1),
('Yarumal','Yarumal',1),
('Yolombó','Yolombó',1),
('Yondó Casabe','Yondó Casabe',1),
('Yopal','Yopal',26),
('Yotoco','Yotoco',24),
('Yumbo','Yumbo',24),
('Zambrano','Zambrano',4),
('Zapatoca','Zapatoca',21),
('Zapayán PUNTA DE PIEDRAS','Zapayán PUNTA DE PIEDRAS',15),
('Zaragoza','Zaragoza',1),
('Zarzal','Zarzal',24),
('Zetaquirá','Zetaquirá',5),
('Zipacón','Zipacón',11),
('Zipaquirá','Zipaquirá',11),
('Zona Bananera PRADO - SEVILLA','Zona Bananera PRADO - SEVILLA',15),
('Ábrego','Ábrego',18),
('Íquira','Íquira',13),
('Úmbita','Úmbita',5),
('Útica','Útica',11);


	