package com.gell.psews.negocio.servicio;

import java.math.BigDecimal;
import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 *
 */
@WebService(name = "PSEHostingWSSoap", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS")
@HandlerChain(file = "PSEHostingWS_handler.xml")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PSEHostingWSSoap {

    /**
     *
     * @param amount
     * @param serviceCode
     * @param paymentID
     * @param entityUrl
     * @param ticketOfficeID
     * @param referenceNumber3
     * @param fields
     * @param referenceNumber2
     * @param vatAmount
     * @param referenceNumber1
     * @param email
     * @param paymentDescription
     * @return returns
     * com.gell.psews.negocio.servicio.PSEHostingCreateTransactionReturn
     */
    @WebMethod(action = "http://www.achcolombia.com.co/PSEHostingWS/createTransactionPaymentHosting")
    @WebResult(name = "createTransactionPaymentHostingResult", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS")
    @RequestWrapper(localName = "createTransactionPaymentHosting", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS", className = "com.gell.psews.negocio.servicio.CreateTransactionPaymentHosting")
    @ResponseWrapper(localName = "createTransactionPaymentHostingResponse", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS", className = "com.gell.psews.negocio.servicio.CreateTransactionPaymentHostingResponse")
    public PSEHostingCreateTransactionReturn createTransactionPaymentHosting(
            @WebParam(name = "ticketOfficeID", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") int ticketOfficeID,
            @WebParam(name = "amount", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") BigDecimal amount,
            @WebParam(name = "vatAmount", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") BigDecimal vatAmount,
            @WebParam(name = "paymentID", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String paymentID,
            @WebParam(name = "paymentDescription", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String paymentDescription,
            @WebParam(name = "referenceNumber1", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String referenceNumber1,
            @WebParam(name = "referenceNumber2", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String referenceNumber2,
            @WebParam(name = "referenceNumber3", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String referenceNumber3,
            @WebParam(name = "serviceCode", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String serviceCode,
            @WebParam(name = "email", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String email,
            @WebParam(name = "fields", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") ArrayOfPSEHostingField fields,
            @WebParam(name = "entity_url", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String entityUrl);

    /**
     *
     * @param memberservices
     * @param amount
     * @param serviceCode
     * @param vatAmount
     * @param paymentDescription
     * @param paymentID
     * @param entityUrl
     * @param ticketOfficeID
     * @param referenceNumber3
     * @param fields
     * @param referenceNumber2
     * @param referenceNumber1
     * @param email
     * @return returns
     * com.gell.psews.negocio.servicio.PSEHostingCreateTransactionReturn
     */
    @WebMethod(action = "http://www.achcolombia.com.co/PSEHostingWS/createTransactionPaymentMulticreditHosting")
    @WebResult(name = "createTransactionPaymentMulticreditHostingResult", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS")
    @RequestWrapper(localName = "createTransactionPaymentMulticreditHosting", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS", className = "com.gell.psews.negocio.servicio.CreateTransactionPaymentMulticreditHosting")
    @ResponseWrapper(localName = "createTransactionPaymentMulticreditHostingResponse", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS", className = "com.gell.psews.negocio.servicio.CreateTransactionPaymentMulticreditHostingResponse")
    public PSEHostingCreateTransactionReturn createTransactionPaymentMulticreditHosting(
            @WebParam(name = "ticketOfficeID", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") int ticketOfficeID,
            @WebParam(name = "amount", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") BigDecimal amount,
            @WebParam(name = "vatAmount", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") BigDecimal vatAmount,
            @WebParam(name = "paymentID", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String paymentID,
            @WebParam(name = "paymentDescription", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String paymentDescription,
            @WebParam(name = "referenceNumber1", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String referenceNumber1,
            @WebParam(name = "referenceNumber2", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String referenceNumber2,
            @WebParam(name = "referenceNumber3", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String referenceNumber3,
            @WebParam(name = "serviceCode", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String serviceCode,
            @WebParam(name = "email", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String email,
            @WebParam(name = "fields", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") ArrayOfPSEHostingField fields,
            @WebParam(name = "memberservices", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") ArrayOfPSEHostingMemberService memberservices,
            @WebParam(name = "entity_url", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String entityUrl);

    /**
     *
     * @param password
     * @param paymentID
     * @param ticketOfficeID
     * @return returns
     * com.gell.psews.negocio.servicio.PSEHostingTransactionInformationReturn
     */
    @WebMethod(action = "http://www.achcolombia.com.co/PSEHostingWS/getTransactionInformationHosting")
    @WebResult(name = "getTransactionInformationHostingResult", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS")
    @RequestWrapper(localName = "getTransactionInformationHosting", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS", className = "com.gell.psews.negocio.servicio.GetTransactionInformationHosting")
    @ResponseWrapper(localName = "getTransactionInformationHostingResponse", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS", className = "com.gell.psews.negocio.servicio.GetTransactionInformationHostingResponse")
    public PSEHostingTransactionInformationReturn getTransactionInformationHosting(
            @WebParam(name = "ticketOfficeID", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") int ticketOfficeID,
            @WebParam(name = "password", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String password,
            @WebParam(name = "paymentID", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String paymentID);

    /**
     *
     * @param amount
     * @param providerCode
     * @param paymentID
     * @param entityUrl
     * @param ticketOfficeID
     * @param referenceNumber3
     * @param fields
     * @param referenceNumber2
     * @param vatAmount
     * @param referenceNumber1
     * @param email
     * @param paymentDescription
     * @return returns
     * com.gell.psews.negocio.servicio.PSEHostingCreateTransactionReturn
     */
    @WebMethod(action = "http://www.achcolombia.com.co/PSEHostingWS/createCreditCardPaymentHosting")
    @WebResult(name = "createCreditCardPaymentHostingResult", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS")
    @RequestWrapper(localName = "createCreditCardPaymentHosting", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS", className = "com.gell.psews.negocio.servicio.CreateCreditCardPaymentHosting")
    @ResponseWrapper(localName = "createCreditCardPaymentHostingResponse", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS", className = "com.gell.psews.negocio.servicio.CreateCreditCardPaymentHostingResponse")
    public PSEHostingCreateTransactionReturn createCreditCardPaymentHosting(
            @WebParam(name = "ticketOfficeID", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") int ticketOfficeID,
            @WebParam(name = "amount", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") BigDecimal amount,
            @WebParam(name = "vatAmount", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") BigDecimal vatAmount,
            @WebParam(name = "paymentID", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String paymentID,
            @WebParam(name = "paymentDescription", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String paymentDescription,
            @WebParam(name = "referenceNumber1", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String referenceNumber1,
            @WebParam(name = "referenceNumber2", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String referenceNumber2,
            @WebParam(name = "referenceNumber3", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String referenceNumber3,
            @WebParam(name = "providerCode", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String providerCode,
            @WebParam(name = "email", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String email,
            @WebParam(name = "fields", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") ArrayOfPSEHostingField fields,
            @WebParam(name = "entity_url", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String entityUrl);

    /**
     *
     * @param password
     * @param paymentID
     * @param ticketOfficeID
     * @return returns
     * com.gell.psews.negocio.servicio.PSEHostingCreditCardInformationReturn
     */
    @WebMethod(action = "http://www.achcolombia.com.co/PSEHostingWS/getCreditCardInformationHosting")
    @WebResult(name = "getCreditCardInformationHostingResult", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS")
    @RequestWrapper(localName = "getCreditCardInformationHosting", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS", className = "com.gell.psews.negocio.servicio.GetCreditCardInformationHosting")
    @ResponseWrapper(localName = "getCreditCardInformationHostingResponse", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS", className = "com.gell.psews.negocio.servicio.GetCreditCardInformationHostingResponse")
    public PSEHostingCreditCardInformationReturn getCreditCardInformationHosting(
            @WebParam(name = "ticketOfficeID", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") int ticketOfficeID,
            @WebParam(name = "password", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String password,
            @WebParam(name = "paymentID", targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS") String paymentID);

}
