package com.gell.psews.negocio.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 *
 */
@WebServiceClient(
        name = "PSEHostingWS",
        targetNamespace = "http://www.achcolombia.com.co/PSEHostingWS"/*,
        wsdlLocation = "https://200.1.124.65/PSEHostingWebServices/PSEHostingWS.asmx?wsdl"*/
)
@HandlerChain(file = "PSEHostingWS_handler.xml")
public class PSEHostingWS extends Service
{

  private final static QName PSEHOSTINGWS_QNAME = new QName("http://www.achcolombia.com.co/PSEHostingWS", "PSEHostingWS");

  public PSEHostingWS(URL wsdlLocation)
  {
    super(wsdlLocation, PSEHOSTINGWS_QNAME);
  }

  public PSEHostingWS(URL wsdlLocation, WebServiceFeature... features)
  {
    super(wsdlLocation, PSEHOSTINGWS_QNAME, features);
  }

  public PSEHostingWS(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  public PSEHostingWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features)
  {
    super(wsdlLocation, serviceName, features);
  }

  /**
   *
   * @return returns PSEHostingWSSoap
   */
  @WebEndpoint(name = "PSEHostingWSSoap")
  public PSEHostingWSSoap getPSEHostingWSSoap()
  {
    return super.getPort(new QName("http://www.achcolombia.com.co/PSEHostingWS", "PSEHostingWSSoap"), PSEHostingWSSoap.class);
  }

  /**
   *
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
   * configure on the proxy. Supported features not in the <code>features</code>
   * parameter will have their default values.
   * @return returns PSEHostingWSSoap
   */
  @WebEndpoint(name = "PSEHostingWSSoap")
  public PSEHostingWSSoap getPSEHostingWSSoap(WebServiceFeature... features)
  {
    return super.getPort(new QName("http://www.achcolombia.com.co/PSEHostingWS", "PSEHostingWSSoap"), PSEHostingWSSoap.class, features);
  }

  /**
   *
   * @return returns PSEHostingWSSoap
   */
  @WebEndpoint(name = "PSEHostingWSSoap12")
  public PSEHostingWSSoap getPSEHostingWSSoap12()
  {
    return super.getPort(new QName("http://www.achcolombia.com.co/PSEHostingWS", "PSEHostingWSSoap12"), PSEHostingWSSoap.class);
  }

  /**
   *
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
   * configure on the proxy. Supported features not in the <code>features</code>
   * parameter will have their default values.
   * @return returns PSEHostingWSSoap
   */
  @WebEndpoint(name = "PSEHostingWSSoap12")
  public PSEHostingWSSoap getPSEHostingWSSoap12(WebServiceFeature... features)
  {
    return super.getPort(new QName("http://www.achcolombia.com.co/PSEHostingWS", "PSEHostingWSSoap12"), PSEHostingWSSoap.class, features);
  }

  private URL __getWsdlLocation(String urlWebservices)
  {
    try {
      return new URL("https://200.1.124.65/PSEHostingWebServices/PSEHostingWS.asmx?wsdl");
    } catch (MalformedURLException ex) {
      throw new WebServiceException(ex);
    }
  }

}
