package com.bioagricola.common.util;

public enum ENUM_IMCOL_TIPO_RESOLUCION {
	DIRECTA,
	FUNCION,
	SQL_SINGLE_SELECT,
	HOMOLOGACION,
	CONSTANTE,
	NULL,
	REFERENCIA,
	SQL_VARIANTE_SELECT,
	MAP_GLOBAL,
}