## default connection pool
spring.datasource.hikari.connectionTimeout=1000000
spring.datasource.hikari.maximumPoolSize=5


spring.datasource.tomcat.max-active=1
spring.datasource.hikari.max-lifetime = 600000
## PostgreSQL
spring.datasource.url=jdbc:postgresql://10.43.51.29:5432/Tecnicoaseo
spring.datasource.username=olsoftware
spring.datasource.password=n3Lc0SeVvufblVZMDWkZ

server.port=8080

