## default connection pool
spring.datasource.hikari.connectionTimeout=1000000
spring.datasource.hikari.maximumPoolSize=5


spring.datasource.tomcat.max-active=1
spring.datasource.hikari.max-lifetime = 600000
## PostgreSQL
#spring.datasource.url=jdbc:postgresql://10.43.51.29:5432/Tecnicoaseo
#spring.datasource.username=olsoftware
#spring.datasource.password=n3Lc0SeVvufblVZMDWkZ
spring.datasource.url=jdbc:postgresql://10.43.51.30:5432/Tecnico
spring.datasource.username=postgres
spring.datasource.password=Admpos1650.

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

