#spring.datasource.jndi-name=java:/PostgresDS
aseo.datasource.driver-class-name=org.postgresql.Driver
aseo.datasource.url=jdbc:postgresql://10.43.51.169:5432/Tecnico
aseo.datasource.username=postgres
aseo.datasource.password=Coserver.10*
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=none
server.port=9091
spring.jmx.default-domain=asesoftware
# Conexiones a base de datos
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.max-lifetime=40000 
server.tomcat.max-threads=400
spring.datasource.hikari.idle-timeout=10000 
spring.jpa.show-sql=false
# Conexi\u00f3n Seven
seven.datasource.url=jdbc:sqlserver://10.43.51.27;database=seven
seven.datasource.username=gellppto
seven.datasource.password=GLlPpto7++
seven.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

logging.level.org.springframework=ERROR
logging.level.org.springframework.web=INFO 
logging.level.com.bioagricola.apirest=ERROR
logging.file.name=/opt/wildfly/standalone/log/gellapiaprovechamiento_log4.log
