apply from: "$rootProject.projectDir/hya.gradle"
apply plugin: 'org.jetbrains.kotlin.android'

android {

    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES']
        }
    }
    namespace 'com.progracol.hya'
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.5.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.5.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1'
    implementation 'com.google.android.material:material:1.7.0'

    hilt()
    lifecycle()
    arcgis()
    material()
    gson()
    images()

    /*hilt()
    gson()
    lifecycle()

    arcgis()
    images()
    carousel()*/

    api project(path: ':core')

}