## default connection pool
spring.datasource.hikari.connectionTimeout=1000000
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.minimum-idle= 10
spring.datasource.hikari.maximum-pool-size= 20
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime= 1800000
#spring.datasource.hikari.max-idle=3

##Productivo (IP interna)
#spring.datasource.url=jdbc:postgresql://10.43.51.29:5432/Tecnicoaseo
#spring.datasource.url=jdbc:postgresql://10.43.51.68:5432/Tecnico?stringtype=unspecified
#spring.datasource.url=jdbc:postgresql://10.43.51.80:5432/tecnicoetl?stringtype=unspecified
#spring.datasource.url=jdbc:postgresql://10.43.51.80:5432/tecnico169?stringtype=unspecified
spring.datasource.url=jdbc:postgresql://10.43.51.169:5432/Tecnico?stringtype=unspecified
#spring.datasource.url=jdbc:postgresql://10.43.51.190:5432/Tecnico?stringtype=unspecified
#spring.datasource.hikari.jdbc-url=jdbc:postgresql://10.43.51.29:5432/Tecnicoaseo?stringtype=unspecified
#spring.datasource.jndi-name=java:/PoolTecnicoAseo29

##Pruebas
#spring.datasource.url = jdbc:postgresql://190.14.232.148:7432/Tecnicoaseo?stringtype=unspecified
#spring.datasource.hikari.jdbc-url=jdbc:postgresql://190.14.232.148:7432/Tecnicoaseo?stringtype=unspecified
spring.datasource.hikari.username= postgres
spring.datasource.hikari.password= Coserver.10*
#spring.datasource.hikari.username= postgres
#spring.datasource.hikari.password= Admpos1650.
#spring.datasource.hikari.username= jlmendoza
#spring.datasource.hikari.password=3696dd90fe5473c4f273e220ca3cac49
#spring.datasource.hikari.username= asesoftTest
#spring.datasource.hikari.password=Yk33SW94TShQCqzZdojZuVNJ3Kynemv52q


#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=com.bioagricola.common.entity.dialect.BioagricolaCustomPostgreSqlDialect
#spring.mvc.converters.preferred-json-mapper=jackson

spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.show-sql=false

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=1000
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework=ERROR
spring.main.banner-mode=off
logging.level.com.bioagricola=INFO
logging.file.name=/opt/wildfly/standalone/log/gellapihomafo_log4.log

spring.data.web.pageable.default-page-size=2000
server.servlet.contextPath=/homafo

spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# multipart
#multipart.enabled=true
spring.servlet.multipart.enabled= true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size = 100MB
spring.http.multipart.max-file-size=10MB
spring.http.multipart.max-request-size=100MB
#multipart.enabled=true
#spring.http.multipart.max-file-size=2MB
#spring.http.multipart.max-request-size=100MB

url.az=http://10.43.51.30:8080
#gell.estandar.api.autenticador.url=http://10.43.51.168:8080
gell.estandar.api.autenticador.url=http://10.43.51.30:8080
#spring.devtools.restart.enabled=false
spring.devtools.restart.additional-exclude=org/springframework/web/multipart/**
#gell.estandar.api.autenticador.url=http://190.14.232.146:8081
#gell.estandar.api.autenticador.url=http://190.14.232.146:8081
#gell.estandar.api.autenticador.url=http://localhost:8080
#spring.datasource.primary.jndi-name=java:/jdbc/bioagricola
#spring.datasource.jdbcUrl=jdbc:postgresql://190.14.232.148:7432/Tecnicoaseo?stringtype=unspecified

# Email properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.devtools.restart.enabled=false
restart.include.multipartfile=false