##Productivo (IP interna)
#spring.datasource.jdbc-url=jdbc:postgresql://10.43.51.29:5432/Tecnicoaseo?stringtype=unspecified
#spring.datasource.jndi-name=java:/PoolTecnicoAseo29

##Pruebas
spring.datasource.jdbc-url=jdbc:postgresql://10.43.51.68:5432/Tecnico?stringtype=unspecified
spring.datasource.username=jlmendoza
spring.datasource.password=3696dd90fe5473c4f273e220ca3cac49