#rugii_rugii_homepage:
#    resource: "@RugiiRugiiBundle/Controller/DefaultController.php"
#    prefix:   /
#    type:     annotation
#    pattern:  /
#    defaults: { _controller: RugiiRugiiBundle:Default:index }

rugii_rugii_loginpage:
#    resource: "@RugiiRugiiBundle/Controller/DefaultController.php"
#    type: annotation
     pattern:  /
     defaults: { _controller: RugiiRugiiBundle:Default:index }

rugii_rugii_session:
     pattern:  /session
     defaults: { _controller: RugiiRugiiBundle:Default:index }