// user authentication
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const CLEAR_AUTHENTICATED = "CLEAR_AUTHENTICATED";
export const LOAD_USER = "LOAD_USER";

//---aforo normal main search (consultar table)
export const LOAD_AFOROS_RESULT = "LOAD_AFOROS_RESULT";
export const CLEAR_AFOROS_RESULT = "CLEAR_AFOROS_RESULT";

// Aforo Selects
export const LOAD_TIPOS_AFORO = "LOAD_TIPOS_AFORO";
export const LOAD_FRECUENCIA_RECOLECCION = "LOAD_FRECUENCIA_RECOLECCION";
export const LOAD_TECNICO_AFORADOR = "LOAD_TECNICO_AFORADOR";
export const LOAD_CONCEPTO_AFORO = "LOAD_CONCEPTO_AFORO";
export const LOAD_BARRIO = "LOAD_BARRIO";
export const LOAD_MUNICIPIO = "LOAD_MUNICIPIO";
export const LOAD_TIPO_GENERADOR = "LOAD_TIPO_GENERADOR";
export const LOAD_ACTIVIDAD = "LOAD_ACTIVIDAD";
export const LOAD_ESTADO = "LOAD_ESTADO";
export const LOAD_DEPARTAMENTO = "LOAD_DEPARTAMENTO";
export const LOAD_TIPO_USO = "LOAD_TIPO_USO";
export const LOAD_CICLO = "LOAD_CICLO";
export const LOAD_RUTA = "LOAD_RUTA";
export const LOAD_ESTRATO = "LOAD_ESTRATO";
export const LOAD_UBICACION = "LOAD_UBICACION";

export const LOAD_RUTAMICROMACRO = "LOAD_RUTAMICROMACRO";
//Aforo table  Multiusuario
export const LOAD_AFOROSMULTI_RESULT = "LOAD_AFOROSMULTI_RESULT";
export const CLEAR_AFOROSMULTI_RESULT = "CLEAR_AFOROSMULTI_RESULT";
///selectS aforo multi
export const LOAD_NOMBRES_AFORO_MULTI = "LOAD_NOMBRES_AFORO_MULTI";
export const LOAD_DEPARTAMENTO_AFORO_MULTI = "LOAD_DEPARTAMENTO_AFORO_MULTI";
export const LOAD_MUNICIPIO_AFORO_MULTI = "LOAD_MUNICIPIO_AFORO_MULTI";
export const LOAD_BARRIO_AFORO__MULTI = "LOAD_BARRIO_MULTI";
//SELECTS aforo multi Nuevo
export const LOAD_NUEVO_SUSCRIPCIONES_MULTI = "LOAD_NUEVO_SUSCRIPCIONES_MULTI";
export const LOAD_TIPOS_DISTRIBUCION = "LOAD_TIPOS_DISTRIBUCION";
//VISITAS AFOROS
export const LOAD_AFOROS_VISITAS_RESULT = "LOAD_AFOROS_VISITAS_RESULT";
export const CLEAR_AFOROS_VISITAS_RESULT = "CLEAR_AFOROS_VISITAS_RESULT";
//AFOROS HISTORICOS
export const LOAD_AFOROS_HISTORICOS_RESULT = "LOAD_AFOROS_HISTORICOS_RESULT";
export const CLEAR_AFOROS_HISTORICOS_RESULT = "CLEAR_AFOROS_HISTORICOS_RESULT";
//SUSCRIPCIONES
export const LOAD_CIUDADES_RESULT = "LOAD_SUSCRIPCIONES_RESULT";
export const CLEAR_CIUDADES_RESULT = "CLEAR_SUSCRIPCIONES_RESULT";

export const LOAD_TIPO_IDENTIFICACION = "LOAD_TIPO_IDENTIFICACION";
export const CLEAR_TIPO_IDENTIFICACION = "CLEAR_TIPO_IDENTIFICACION";

export const LOAD_TIPO_PERSONA = "LOAD_TIPO_PERSONA";
export const CLEAR_TIPO_PERSONA = "CLEAR_TIPO_PERSONA";

export const LOAD_MUNICIPIOS = "LOAD_MUNICIPIOS";
export const CLEAR_MUNICIPIOS = "CLEAR_MUNICIPIOS";

export const LOAD_BARRIOS = "LOAD_BARRIOS";
export const CLEAR_BARRIOS = "CLEAR_BARRIOS";

//SUSCRIPCIONES TERCEROS
export const LOAD_BUSCAR_TERCEROS_RESULT = "LOAD_BUSCAR_TERCEROS_RESULT";
export const CLEAR_BUSCAR_TERCEROS_RESULT = "CLEAR_BUSCAR_TERCEROS_RESULT";
export const LOAD_CLASIFICACION_TERCEROS_RESULT =
  "LOAD_CLASIFICACION_TERCEROS_RESULT";
export const CLEAR_CLASIFICACION_TERCEROS_RESULT =
  "CLEAR_CLASIFICACION_TERCEROS_RESULT";
export const LOAD_CREAR_TERCERO = "CREAR_TERCERO";
export const CLEAR_CREAR_TERCERO = "CLEAR_CREAR_TERCERO";

export const LOAD_ACTUALIZAR_TERCERO = "LOAD_ACTUALIZAR_TERCERO";
export const CLEAR_ACTUALIZAR_TERCERO = "CLEAR_ACTUALIZAR_TERCERO";
//SUSCRIPCIONES TERCEROS PROPIEDADES

export const LOAD_BUSCAR_COMPLEMENTOS = "LOAD_BUSCAR_COMPLEMENTOS";
export const CLEAR_BUSCAR_COMPLEMENTOS = "CLEAR_BUSCAR_COMPLEMENTOS";

export const LOAD_TOKEN = "LOAD_TOKEN";
export const CLEAR_TOKEN = "CLEAR_TOKEN";

export const LOAD_GEOLOCALIZAR = "LOAD_GEOLOCALIZAR";
export const CLEAR_GEOLOCALIZAR = "CLEAR_GEOLOCALIZAR";

export const LOAD_CARACTERISTICAS_ARCGIS = "LOAD_CARACTERISTICAS_ARCGIS";
export const CLEAR_CARACTERISTICAS_ARCGIS = "CLEAR_CARACTERISTICAS_ARCGIS";

export const LOAD_CAPAS_MAPA = "LOAD_CAPAS_MAPA";
export const CLEAR_CAPAS_MAPA = "CLEAR_CAPAS_MAPA";

export const LOAD_TIPO_PROPIEDAD = "LOAD_TIPO_PROPIEDAD";
export const CLEAR_TIPO_PROPIEDAD = "CLEAR_TIPO_PROPIEDAD";

export const LOAD_TIPOS_VIVIENDA = "LOAD_TIPOS_VIVIENDA";
export const CLEAR_TIPOS_VIVIENDA = "CLEAR_TIPOS_VIVIENDA";

export const LOAD_CREAR_PROPIEDAD = "LOAD_CREAR_PROPIEDAD";
export const CLEAR_CREAR_PROPIEDAD = "CLEAR_CREAR_PROPIEDAD";

export const LOAD_UPDATE_PROPIEDAD = "LOAD_UPDATE_PROPIEDAD";
export const CLEAR_UPDATE_PROPIEDAD = "CLEAR_UPDATE_PROPIEDAD";

export const LOAD_CLONAR_PROPIEDAD = "LOAD_CLONAR_PROPIEDAD";
export const CLEAR_CLONAR_PROPIEDAD = "CLEAR_CLONAR_PROPIEDAD";

export const LOAD_DELETE_PROPIEDAD = "LOAD_DELETE_PROPIEDAD";
export const CLEAR_DELETE_PROPIEDAD = "CLEAR_DELETE_PROPIEDAD";

export const LOAD_LISTAR_PROPIEDADES_TERCERO =
  "LOAD_LISTAR_PROPIEDADES_TERCERO";
export const CLEAR_LISTAR_PROPIEDADES_TERCERO =
  "CLEAR_LISTAR_PROPIEDADES_TERCERO";

export const LOAD_PROPIEDAD = "LOAD_PROPIEDAD";
export const CLEAR_PROPIEDAD = "LOAD_PROPIEDAD";

//SUSCRIPCIONES SUSCRIPCION Y suscripcionTerceroReducer

export const LOAD_COVENIOS = "LOAD_COVENIOS";
export const CLEAR_COVENIOS = "CLEAR_COVENIOS";

export const LOAD_CREAR_SUSCRIPTOR = "LOAD_CREAR_SUSCRIPTOR";
export const CLEAR_CREAR_SUSCRIPTOR = "CLEAR_CREAR_SUSCRIPTOR";

export const LOAD_CREAR_SUSCRIPCION = "LOAD_CREAR_SUSCRIPCION";
export const CLEAR_CREAR_SUSCRIPCION = "CLEAR_CREAR_SUSCRIPCION";

export const LOAD_EDITAR_SUSCRIPCION = "LOAD_EDITAR_SUSCRIPCION";
export const CLEAR_EDITAR_SUSCRIPCION = "CLEAR_EDITAR_SUSCRIPCION";

export const LOAD_BUSCAR_ID = "LOAD_BUSCAR_ID";
export const CLEAR_BUSCAR_ID = "CLEAR_BUSCAR_ID";

export const LOAD_DETALLE_SUSCRIPCION = "LOAD_DETALLE_SUSCRIPCION";
export const CLEAR_DETALLE_SUSCRIPCION = "CLEAR_DETALLE_SUSCRIPCION";

export const LOAD_PROPIEDADES = "LOAD_PROPIEDADES";
export const CLEAR_PROPIEDADES = "CLEAR_PROPIEDADES";

export const LOAD_SUSCRIPCIONES_TERCERO = "LOAD_SUSCRIPCIONES_TERCERO";
export const CLEAR_SUSCRIPCIONES_TERCERO = "CLEAR_SUSCRIPCIONES_TERCERO";

export const LOAD_FILTRAR_SUSCRIPCION = "LOAD_FILTRAR_SUSCRIPCION";
export const CLEAR_FILTRAR_SUSCRIPCION = "CLEAR_FILTRAR_SUSCRIPCION";

export const LOAD_ESTADOS_SUSCRIPCION = "LOAD_ESTADOS_SUSCRIPCION";
export const CLEAR_ESTADOS_SUSCRIPCION = "CLEAR_ESTADOS_SUSCRIPCION";

export const LOAD_ESTRATOS = "LOAD_ESTRATOS";
export const CLEAR_ESTRATOS = "CLEAR_ESTRATOS";

export const LOAD_TIPOS_USO = "LOAD_TIPOS_USO";
export const CLEAR_TIPOS_USO = "CLEAR_TIPOS_USO";

export const LOAD_LIQUIDACIONES = "LOAD_LIQUIDACIONES";
export const CLEAR_LIQUIDACIONES = "CLEAR_LIQUIDACIONES";

export const LOAD_CICLOS = "LOAD_CICLOS";
export const CLEAR_CICLOS = "CLEAR_CICLOS";

export const LOAD_RUTAS = "LOAD_RUTAS";
export const CLEAR_RUTAS = "CLEAR_RUTAS";

export const LOAD_RUTAS_APROVECHAMIENTO = "LOAD_RUTAS_APROVECHAMIENTO";
export const CLEAR_RUTAS_APROVECHAMIENTO = "CLEAR_RUTAS_APROVECHAMIENTO";

export const LOAD_MACRORUTA = "LOAD_MACRORUTA";
export const CLEAR_MACRORUTA = "CLEAR_MACRORUTA";

export const LOAD_MACRORUTA_BY_ID = "LOAD_MACRORUTA_BY_ID";
export const CLEAR_MACRORUTA_BY_ID = "CLEAR_MACRORUTA_BY_ID";

export const LOAD_HORARIOS = "LOAD_HORARIOS";
export const CLEAR_HORARIOS = "CLEAR_HORARIOS";

export const LOAD_HORARIOS_RUTA = "LOAD_HORARIOS_RUTA";
export const CLEAR_HORARIOS_RUTA = "CLEAR_HORARIOS_RUTA";

export const LOAD_ACTIVIDAD_ECONOMICA = "LOAD_ACTIVIDAD_ECONOMICA";
export const CLEAR_ACTIVIDAD_ECONOMICA = "CLEAR_ACTIVIDAD_ECONOMICA";

export const LOAD_TIPOS_SUSCRIPCION = "LOAD_TIPOS_SUSCRIPCION";
export const CLEAR_TIPOS_SUSCRIPCION = "CLEAR_TIPOS_SUSCRIPCION";

export const LOAD_CONCEPTOS = "LOAD_CONCEPTOS";
export const CLEAR_CONCEPTOS = "CLEAR_CONCEPTOS";

export const LOAD_EMPRESAS = "LOAD_EMPRESAS";
export const CLEAR_EMPRESAS = "CLEAR_EMPRESAS";
// suscripcion homologacion

export const LOAD_BUSCAR_HOMOLOGACION = "LOAD_BUSCAR_HOMOLOGACION";
export const CLEAR_BUSCAR_HOMOLOGACION = "CLEAR_BUSCAR_HOMOLOGACION";

export const LOAD_BUSCAR_HOMOLOGACIONES_HOMOLOGABLES =
  "LOAD_BUSCAR_HOMOLOGACIONES_HOMOLOGABLES";
export const CLEAR_BUSCAR_HOMOLOGACIONES_HOMOLOGABLES =
  "CLEAR_BUSCAR_HOMOLOGACIONES_HOMOLOGABLES";

export const LOAD_DETALLE_SUS_HOMOLOGACION = "LOAD_DETALLE_SUS_HOMOLOGACION";
export const CLEAR_DETALLE_SUS_HOMOLOGACION = "CLEAR_DETALLE_SUS_HOMOLOGACION";

export const LOAD_CONVENIOS_HOMOLOGACION = "LOAD_CONVENIOS_HOMOLOGACION";
export const CLEAR_CONVENIOS_HOMOLOGACION = "CLEAR_CONVENIOS_HOMOLOGACION";

export const LOAD_CONVENIOS_EMPRESA_HOMOLOGACION =
  "LOAD_CONVENIOS_EMPRESA_HOMOLOGACION";
export const CLEAR_CONVENIOS_EMPRESA_HOMOLOGACION =
  "CLEAR_CONVENIOS_EMPRESA_HOMOLOGACION";

export const LOAD_EMPRESA_CONVENIOS_HOMOLOGACION =
  "LOAD_EMPRESA_CONVENIOS_HOMOLOGACION";
export const CLEAR_EMPRESA_CONVENIOS_HOMOLOGACION =
  "CLEAR_EMPRESA_CONVENIOS_HOMOLOGACION";

export const LOAD_CICLOS_HOMOLOGACION = "LOAD_CICLOS_HOMOLOGACION";
export const CLEAR_CICLOS_HOMOLOGACION = "CLEAR_CICLOS_HOMOLOGACION";

export const LOAD_CREAR_HOMOLOGACION = "LOAD_CREAR_HOMOLOGACION";
export const CLEAR_CREAR_HOMOLOGACION = "CLEAR_CREAR_HOMOLOGACION";

export const LOAD_ACTUALIZAR_HOMOLOGACION = "LOAD_ACTUALIZAR_HOMOLOGACION";
export const CLEAR_ACTUALIZAR_HOMOLOGACION = "CLEAR_ACTUALIZAR_HOMOLOGACION";

export const LOAD_SUS_HOMOLOGACION = "LOAD_SUS_HOMOLOGACION";
export const CLEAR_SUS_HOMOLOGACION = "CLEAR_SUS_HOMOLOGACION";

export const LOAD_EMPRESAS_HOMOLOGACION = "LOAD_EMPRESAS_HOMOLOGACION";
export const CLEAR_EMPRESAS_HOMOLOGACION = "CLEAR_EMPRESAS_HOMOLOGACION";
export const LOAD_EMPRESAS_HOMOLOGABLE = "LOAD_EMPRESAS_HOMOLOGABLE";
export const CLEAR_EMPRESAS_HOMOLOGABLE = "CLEAR_EMPRESAS_HOMOLOGABLE";
//tablas gestion
//tablas gestion -- actualizacion
export const LOAD_LISTA_BARRIOS_ASEO = "LOAD_LISTA_BARRIOS_ASEO";
export const LOAD_LISTA_UNIDADES_EDIT = "LOAD_LISTA_UNIDADES_EDIT";

export const LOAD_LISTA_ACTUALIZACION_OTHERS = "LOAD_LISTA_ACTUALIZACION_OTHERS";
export const LOAD_LISTA_ACTUALIZACION_PUNTO = "LOAD_LISTA_ACTUALIZACION_PUNTO";

export const CLEAR_LISTA_ACTUALIZACION_OTHERS = "CLEAR_LISTA_ACTUALIZACION_OTHERS";
export const CLEAR_LISTA_ACTUALIZACION_PUNTO = "CLEAR_LISTA_ACTUALIZACION_PUNTO";

export const LOAD_BUSCAR_ACTUALIZACION = "LOAD_BUSCAR_ACTUALIZACION";
export const CLEAR_BUSCAR_ACTUALIZACION = "CLEAR_BUSCAR_ACTUALIZACION";

export const LOAD_BORRAR_ACTUALIZACION = "LOAD_BORRAR_ACTUALIZACION";
export const CLEAR_BORRAR_ACTUALIZACION = "CLEAR_BORRAR_ACTUALIZACION";

export const LOAD_UPDATE_ACTUALIZACION = "LOAD_UPDATE_ACTUALIZACION";

export const LOAD_APROBAR_ACTUALIZACION = "LOAD_APROBAR_ACTUALIZACION";
export const CLEAR_APROBAR_ACTUALIZACION = "CLEAR_APROBAR_ACTUALIZACION";

export const LOAD_IMAGENES_ACTUALIZACION = "LOAD_IMAGENES_ACTUALIZACION";
export const CLEAR_IMAGENES_ACTUALIZACION = "CLEAR_IMAGENES_ACTUALIZACION";
//tablas gestion -- novedad
export const LOAD_LISTA_NOVEDAD = "LOAD_LISTA_NOVEDAD";
export const CLEAR_LISTA_NOVEDAD = "CLEAR_LISTA_NOVEDAD";

export const LOAD_BORRAR_NOVEDAD = "LOAD_BORRAR_NOVEDAD";
export const CLEAR_BORRAR_NOVEDAD = "CLEAR_BORRAR_NOVEDAD";

export const LOAD_APROBAR_NOVEDAD = "LOAD_APROBAR_NOVEDAD";
export const CLEAR_APROBAR_NOVEDAD = "CLEAR_APROBAR_NOVEDAD";

export const LOAD_IMAGENES_NOVEDAD = "LOAD_IMAGENES_NOVEDAD";
export const CLEAR_IMAGENES_NOVEDAD = "CLEAR_IMAGENES_NOVEDAD";
